### ISSUE TITLE
Client State Management 

### ISSUE THREAD

**Issue by JoshuaLee-NOAA** [JLee2021/pwa-prototype#1]
Mike, I know I plugged the idea of IndexedDB API for client-side state management. However, given the scope of this prototype, you could also just use local storage (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). Eventually, I want to better understand what client-side databases will work best for us, but local storage will do in a pinch.

**Comment by mryan5** [comment]
It makes no difference to me. I will obviously work locally to avoid problems but the difference between local and remote storage is trivial. I can just change the credentials and the path. I do want to use PostgreSQL personally with Next: I found this.
https://www.codeoftheprogrammer.com/2020/01/16/postgresql-from-nextjs-api-route/

**Comment by JoshuaLee-NOAA** [comment]
Right on, I dig it.
